server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wishlist_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml

springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    operationsSorter: method
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: v3

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    enable:
      all: true
  endpoint:
    prometheus:
      enabled: true


jwt:
  secret: x5Xq9PAiHuPFFJ/pG+H45JNQ/yPvNM8jXH3XNhWMp7k=
  refreshSecret: tFlD6u6wpYbtI0KWpVqLxX3CC4t2+YELUSxWYSdtSxk=

logging:
  file:
    name: logs/wishlist.log
  level:
    root: INFO
    com.github.bogdanpronin: DEBUG
    com.fasterxml.jackson.databind: DEBUG
    org.springframework.http.converter.json: DEBUG
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    console: "%d{HH:mm:ss.SSS} %-5level %logger{36} - %msg%n"

